### ISSUE TITLE
Why Drop down the framerate from 60 fps to 30 fps makes the video slow?

### ISSUE THREAD

**Issue by jehadmashhour** [natario1/Transcoder#1]
I have a video with a 60 fps , i tried to compress it with this great library here by drop down the fps to be 30 fps but the problem is the video motion becomes slow .

Mean While i tried to compress the same video with HandBrake ( https://handbrake.fr/ ) on windows with drop down the fps to 30 fps then i didn't see any issue with the video motion .

**Why ?**

Thanks in advance .

**Comment by natario1** [comment]
Can you post the source video?

**Comment by jehadmashhour** [comment]
https://drive.google.com/file/d/1YhaBRLWc9LohYeWdtOs0fv4WtKWZw-Sj/view?usp=drivesdk

Thanks

**Comment by natario1** [comment]
@jehadmashhour I got time only now to look into this issue. If you could post the source video again that would be great! If not I'll close this for now.

**Comment by jehadmashhour** [comment]
@natario1 
Thanks in advance :
https://photos.app.goo.gl/Jj1t5NSFWaGb4E8e9

**Comment by natario1** [comment]
It works well for me with the latest demo app. Give it a try!
