### ISSUE TITLE
Join videos and trimm in a Single Pass

### ISSUE THREAD

**Issue by emlautarom1** [natario1/Transcoder#116]
Hey! Thanks for this awesome library.

I was wondering how I could do the following in the most efficient way:

- Concat 2 videos with no audio into a single one.
- Clip the resulting video to a specified duration.

Both videos have the same settings, and the resulting one should have also the same settings (orientation, bitrate, resolution, and framerate).

Currently, I concatenate both videos and transcode them into a temporary file, then I clip the temporary file into the desired duration. This, as you can imagine, takes too long, especially on weak devices.

**Comment by natario1** [comment]
Sure, you can do it in a single pass if you know the input durations and the output duration.
