### ISSUE TITLE
No sound on output

### ISSUE THREAD

**Issue by lee-ngeap** [natario1/Transcoder#129]
Hi there!

Why no sound after transcoded? Can you please advise?

**Comment by DamonChen117** [comment]
I have the same issue.
Version:0.10.2

Code:
```
val builder = Transcoder.into(trimmedFile.path)
builder.addDataSource(TrackType.AUDIO, TrimDataSource(FilePathDataSource(outputFile.path), startTime * 1000, 0))
...
```

the input file is amr format, the output file is comletely

**Comment by natario1** [comment]
Should be fixed now.
