### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.otaliastudios.transcoder.source.DataSource.isInitialized()' on a null object reference

### ISSUE THREAD

**Issue by jd565** [natario1/Transcoder#154]
Hit this attempting to transcode something from a file path string.

It seems like calling `isInitialized()` hits an NPE as the FilePathDataSource only sets a source once it has been initialized, but checking to see if the data source has been initialized checks if the source (which is still null) has been initialized.

I think a simple fix would be to override the `isInitialized` method for FilePathDataSource to check if the source is null first.

**Comment by humazed** [comment]
Also can confirm it is not happening on 0.9.1

**Comment by hafiz013** [comment]
when this fix version will release?

**Comment by mhackeras** [comment]
I today reproduced this issue. @natario1

**Comment by Mouadabdelghafouraitali** [comment]
Same issue here

**Comment by Mouadabdelghafouraitali** [comment]
Using URI instead of video path fix the issue
