### ISSUE TITLE
Input videos of different rotations

### ISSUE THREAD

**Issue by joeShuff** [natario1/Transcoder#34]
I have four videos, one in each rotation of 0, 90, 180, 270. 

2 of them are 3840x2160 (horizontal) and the other 2 are 2160x3840 (vertical). When I transcode them, the output file is 2160x3840(vertical) and the inputted horizontal clips are trimmed to be 9:16 aspect ration, just like the 2 vertical inputs.

I have tried the following to set the output file to 16:9.

`
transcodeBuilder.setVideoTrackStrategy(DefaultVideoStrategy.Builder()
            .addResizer(AspectRatioResizer(16F / 9F))
            .build())
`

I add the multiple sources to the transcoder using 
`
transcodeBuilder.addDataSource(absoluteFilePath: String)
`

but the output is still vertical. 

This is the case no matter the input order of the videos.

Is there a way to set the aspect ratio to 16:9 and do no chopping on vertical videos, having the black bars is fine.

Thanks for your help

**Comment by natario1** [comment]
No matter the input / output dimensions, the library will never allow the black bars - it will always center crop. 

About choosing between vertical and horizontal, you could use a resizer that returns an ExactSize, like changing AspectRatioResizer so that it returns an ExactSize instead of Size.

**Comment by joeShuff** [comment]
I added the following to my project.
```
class MyExactResizer(val width: Int, val height: Int): Resizer {
    override fun getOutputSize(inputSize: Size): Size {
        return ExactSize(width, height)
    }
}
```

and added it to the transcoder with the following

```
transcodeBuilder.setVideoTrackStrategy(DefaultVideoStrategy.Builder()
            .addResizer(MyExactResizer(1280, 720))
            .build())
```

This results in all horizontal videos (16:9) being shown correctly and all vertical videos (9:16) being chopped in the middle which is better than the other way around. 

Thanks for your help

**Comment by natario1** [comment]
Nice!
