### ISSUE TITLE
Make process Synchronous - WorkManager compatible

### ISSUE THREAD

**Issue by themadmrj** [natario1/Transcoder#35]
Hi,

the androidx WorkManager needs tasks to be synchronous, is there any easy way to make it happen with Transcoder ?
Thanks :)

**Comment by natario1** [comment]
If I remember correctly the transcode() operation returns a `Future`. you can just call `future.get()`.

**Comment by themadmrj** [comment]
Instant response and clean solution. Thanks for the awesome work!!!!
