### ISSUE TITLE
[Feature Request] Add Support for Video Transitions

### ISSUE THREAD

**Issue by seanghay** [natario1/Transcoder#36]
I am really impressed by this library, it's well-designed! 
Do you think it is a good idea to add support for Video Transitions?

There is an open-source transition library called [gl-transitions](https://gl-transitions.com/) which you can take a look at.

**Comment by natario1** [comment]
Thanks!

It would be cool but I don't have any short term plans to work on this. It would be very hard to implement at the moment.

**Comment by seanghay** [comment]
> Thanks!
> 
> It would be cool but I don't have any short term plans to work on this. It would be very hard to implement at the moment.

I have implemented it successfully (took me months of researching 😏) in my company project using `gl-transitions`, however, it may not be fit with this library. But I will look through it and see what I can do to integrate it with this project without breaking it and hopefully will create a pull request in the future.

Thanks for replying!
Love your work!
