### ISSUE TITLE
[Feature Request] Trim time

### ISSUE THREAD

**Issue by aweck** [natario1/Transcoder#37]
Is there a good way to trim the time of a video while transcoding?  Similar to this: https://github.com/ypresto/android-transcoder/pull/14

**Comment by natario1** [comment]
It's not supported at the moment, sorry! If you want to implement on your own, I would use a custom `DataSource` subclass.

**Comment by aweck** [comment]
@natario1 Thanks!  Would you be open to a pull request adding this feature?  It's required for my use case, but I'd prefer if I could check it in here as having a custom lib would make maintenance and updates more painful.

**Comment by natario1** [comment]
Sure! I can give you advices if you need.

The key part that is important to me, is that we should implement this as an isolated component, like a `TrimDataSource` class, without touching the other components in the pipeline.

This way the usage would be:

```java
DataSource source = ...;
DataSource wrapper = new TrimDataSource(source, trimStart, trimEnd);
```

And you could trim separately each segment in case of concatenation.
