### ISSUE TITLE
Trancoding video ON THE GO ?

### ISSUE THREAD

**Issue by Nikhil-z** [natario1/Transcoder#56]
Hey Is there any possibility to add transcoding for a LIVE media streaming URL and play that transcoded video at the same time on Exo player or any other media player.

**Comment by natario1** [comment]
No, sorry! To play you don't need to transcode, you would just need to decode and display.

**Comment by Nikhil-z** [comment]
I was trying to play an m3u8 URL with a variable bitrate. As the audio is in MPEG 2 format the newer android devices don't support it so in newer devices it's just only playing Video and the audio is missing. Do you have any open suggestion regarding the same?

**Comment by natario1** [comment]
No, if device does not have the proper decoder, even Transcoder would fail

**Comment by Nikhil-z** [comment]
Thanks buddy
