### ISSUE TITLE
kotlin

### ISSUE THREAD

**Issue by flashiran1** [natario1/Transcoder#58]
please convert source to kotlin

**Comment by natario1** [comment]
Why?

**Comment by flashiran1** [comment]
Because the Android maker is moving towards it
And most projects are with kotlin today
And kotlin is more in line with kotlin

**Comment by Roberto7588** [comment]
@flashiran1 
-Actually most  projects, at this very moment, are around 99.999% made in Java.
-Google is not moving away from Java at all, and it will stay.
-The fact that Kotlin has been made also an official supported language, it doesn't mean that now you have to migrate everything to such langauge.
-You can also write projects in C++ in Android. 
-To have Kotlin it only means that now Android supports 3 languages: Java, Kolin, and C/C++. 
All of them with the same level of importance. Is up to the developer to choose his preferred one.

**Comment by flashiran1** [comment]
99.999%  please source

**Comment by Roberto7588** [comment]
The first Android version was released in the year 2008, 12 years ago.
Kotlin has only recently been  made official. it didn't even exist when Android appeared. Make your numbers.

**Comment by flashiran1** [comment]
There is no reason for 99.999% percent to use Java
Then, because, for example, we shouldn't refer her to her age! That's not the reason

**Comment by natario1** [comment]
If we can improve the API surface to be more Kotlin-friendly, feel free to suggest how/where and I will consider doing it! I have no plans to transcode the library to Kotlin though, I don't see any benefit in doing so.
