### ISSUE TITLE
DataSink FileDescriptor support

### ISSUE THREAD

**Issue by mudar** [natario1/Transcoder#87]
Hi Mattia, I hope you're doing fine...

I'm creating this issue to link it to a PR: the `DefaultDataSink` constructor relies on the file path. I feel it would be useful to add a constructor that uses a `FileDescriptor`,  especially for Android 10. 

thanks,
mudar

**Comment by natario1** [comment]
Thanks! :-)

**Comment by natario1** [comment]
Also if you want to release a 0.9.1 with this, feel free to do so, I have added you as collaborator. Refer to https://github.com/natario1/Transcoder/commit/e10f83de3aad92973ec2e07a652890ae64918d0f as example to what is needed to prepare a release. Then just create a GitHub Release and CI should push to jcenter
